title: "Shuotao Xu"
email: shuotaoxu at microsoft dot com
description: "Senior Researcher @ Microsoft Research Asia. AI Infrastructure & Chip Design."
url: "https://xushuotao.github.io"
baseurl: ""
theme: minima
plugins:
  - jekyll-feed
